name: Performance benchmark

on:
  workflow_dispatch:
    inputs:
      baseline:
        description: "Baseline Prettier commit"
        required: true

      target:
        description: "Target Prettier commit"
        required: true

      runs:
        description: "Number of runs"
        required: true
        default: 10

env:
  node_version: 20
  hyperfine_version: 1.16.1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node_version }}

      - name: Install dependencies
        run: npm install

      - name: Install misc. dependencies
        run: |
          wget https://github.com/sharkdp/hyperfine/releases/download/v${{ env.hyperfine_version }}/hyperfine_${{ env.hyperfine_version }}_amd64.deb
          sudo dpkg -i hyperfine_${{ env.hyperfine_version }}_amd64.deb

      - name: Run benchmark
        run: node ./scripts/benchmark.js --fo
